# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build UI & Release

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
        cache-dependency-path: 'ui/package-lock.json'

    - name: Build
      shell: bash
      run: |
        cd "${GITHUB_WORKSPACE}/ui"
        npm ci
        ./build.sh

    - name: Get latest release of NodeJS
      uses: rez0n/actions-github-release@main
      id: current_release
      env:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: "marcone/teslausb"
        type: "latest"

    - name: Upload files to a GitHub release
      uses: svenstaro/upload-release-action@2.2.1
      with:
        tag: ${{ steps.current_release.outputs.release }}
        file: teslausb-ui.tgz
        overwrite: false
        repo_token: ${{ secrets.GITHUB_TOKEN }}
